import type { Difficulty, GroupSize } from "@swtor/shared";
import type { Operation } from "./types.js";

/**
 * Zone ids are only listed where an `AreaEntered` line in the sample corpus
 * confirmed them. The rest match on name until a log proves the id, because a
 * guessed id would fail silently while a missing one simply falls back.
 *
 * `difficulties` and `groupSizes` come from the tactical briefings rather than
 * from logs: Master Mode was retired for the launch operations and never built
 * for several later ones, and R-4 Anomaly is 8-player only.
 */

const ALL: Difficulty[] = ["Story", "Veteran", "Master"];
const NO_MASTER: Difficulty[] = ["Story", "Veteran"];
const EIGHT_AND_SIXTEEN: GroupSize[] = [8, 16];
const EIGHT_ONLY: GroupSize[] = [8];

export const OPERATIONS: readonly Operation[] = [
  {
    id: "ev",
    name: "The Eternity Vault",
    location: "Belsavis",
    zoneIds: ["833571547775670"],
    zoneNames: ["eternity vault"],
    isLair: false,
    difficulties: NO_MASTER,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "kp",
    name: "Karagga's Palace",
    location: "Hutta",
    zoneIds: ["833571547775669"],
    zoneNames: ["karagga's palace"],
    isLair: false,
    difficulties: NO_MASTER,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "ec",
    name: "Explosive Conflict",
    location: "Denova",
    zoneIds: ["833571547775688"],
    zoneNames: ["denova"],
    isLair: false,
    difficulties: ALL,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "tfb",
    name: "Terror From Beyond",
    location: "Asation",
    zoneIds: [],
    zoneNames: ["asation", "terror from beyond"],
    isLair: false,
    difficulties: ALL,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "snv",
    name: "Scum and Villainy",
    location: "Darvannis",
    zoneIds: ["137438993037"],
    zoneNames: ["darvannis"],
    isLair: false,
    difficulties: ALL,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "df",
    name: "Dread Fortress",
    location: "Oricon",
    zoneIds: [],
    zoneNames: ["dread fortress"],
    isLair: false,
    difficulties: ALL,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "dp",
    name: "Dread Palace",
    location: "Oricon",
    zoneIds: [],
    zoneNames: ["dread palace"],
    isLair: false,
    difficulties: ALL,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "rav",
    name: "The Ravagers",
    location: "Rishi",
    zoneIds: [],
    zoneNames: ["the ravagers", "ravagers"],
    isLair: false,
    difficulties: NO_MASTER,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "tos",
    name: "Temple of Sacrifice",
    location: "Yavin 4",
    zoneIds: [],
    zoneNames: ["temple of sacrifice"],
    isLair: false,
    difficulties: NO_MASTER,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "gotm",
    name: "Gods from the Machine",
    location: "Iokath",
    zoneIds: [],
    zoneNames: ["gods from the machine", "iokath"],
    isLair: false,
    difficulties: ALL,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "dxun",
    name: "The Nature of Progress",
    location: "Dxun",
    zoneIds: [],
    zoneNames: ["the nature of progress", "dxun"],
    isLair: false,
    difficulties: ALL,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "r4",
    name: "R-4 Anomaly",
    location: "Deep Space Platform",
    zoneIds: [],
    zoneNames: ["r-4 anomaly"],
    isLair: false,
    difficulties: NO_MASTER,
    groupSizes: EIGHT_ONLY,
  },
  {
    id: "lair",
    name: "Lair Operations",
    location: "Various",
    zoneIds: [],
    zoneNames: ["toborro's courtyard", "valley of the machine gods", "hive of the mountain queen"],
    isLair: true,
    difficulties: NO_MASTER,
    groupSizes: EIGHT_AND_SIXTEEN,
  },
  {
    id: "fp_ess",
    name: "The Esseles",
    location: "Coruscant Sector",
    zoneIds: [],
    zoneNames: ["the esseles", "coruscant sector"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_bt",
    name: "The Black Talon",
    location: "Deep Space Transit",
    zoneIds: [],
    zoneNames: ["the black talon", "deep space transit"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_hs",
    name: "Hammer Station",
    location: "Asteroid Belt",
    zoneIds: [],
    zoneNames: ["hammer station", "asteroid belt"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_athiss",
    name: "Athiss",
    location: "Ancient Tomb",
    zoneIds: [],
    zoneNames: ["athiss", "ancient tomb"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_mr",
    name: "Mandalorian Raiders",
    location: "Deep Space",
    zoneIds: [],
    zoneNames: ["mandalorian raiders", "deep space"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_cad",
    name: "Cademimu",
    location: "Cademimu V",
    zoneIds: [],
    zoneNames: ["cademimu", "cademimu v"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_tv",
    name: "Taral V",
    location: "Jungle Outpost",
    zoneIds: [],
    zoneNames: ["taral v", "jungle outpost"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_bp",
    name: "Boarding Party",
    location: "Republic Cruiser",
    zoneIds: [],
    zoneNames: ["boarding party", "republic cruiser"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_mp",
    name: "Maelstrom Prison",
    location: "Deep Space",
    zoneIds: [],
    zoneNames: ["maelstrom prison", "deep space"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_foundry",
    name: "The Foundry",
    location: "Deep Space Factory",
    zoneIds: [],
    zoneNames: ["the foundry", "deep space factory"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_d7",
    name: "Directive 7",
    location: "Cademimu Outpost",
    zoneIds: [],
    zoneNames: ["directive 7", "cademimu outpost"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_boi",
    name: "The Battle of Ilum",
    location: "Ilum Surface",
    zoneIds: [],
    zoneNames: ["the battle of ilum", "ilum surface"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_fe",
    name: "The False Emperor",
    location: "Ilum Stealth Station",
    zoneIds: [],
    zoneNames: ["the false emperor", "ilum stealth station"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_li",
    name: "Lost Island",
    location: "Ord Mantell",
    zoneIds: [],
    zoneNames: ["lost island", "ord mantell"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_kaon",
    name: "Kaon Under Siege",
    location: "Tion Hegemony",
    zoneIds: [],
    zoneNames: ["kaon under siege", "tion hegemony"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_czlabs",
    name: "Czerka Corporate Labs",
    location: "CZ-198",
    zoneIds: [],
    zoneNames: ["czerka corporate labs", "cz-198"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_czcore",
    name: "Czerka Core Meltdown",
    location: "CZ-198",
    zoneIds: [],
    zoneNames: ["czerka core meltdown", "cz-198"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_aot",
    name: "Assault on Tython",
    location: "Jedi Temple Ruins",
    zoneIds: [],
    zoneNames: ["assault on tython", "jedi temple ruins"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_ki",
    name: "Korriban Incursion",
    location: "Sith Academy",
    zoneIds: [],
    zoneNames: ["korriban incursion", "sith academy"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_manaan",
    name: "Depths of Manaan",
    location: "Underwater Laboratory",
    zoneIds: [],
    zoneNames: ["depths of maanan", "underwater laboratory"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_rakata",
    name: "Legacy of the Rakata",
    location: "Rakata Prime",
    zoneIds: [],
    zoneNames: ["legacy of the rakata", "rakata prime"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_bh",
    name: "Blood Hunt",
    location: "Rishi",
    zoneIds: [],
    zoneNames: ["blood hunt", "rishi"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_rishi",
    name: "Battle of Rishi",
    location: "Rishi Island Base",
    zoneIds: [],
    zoneNames: ["battle of rishi", "rishi island base"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_umbara",
    name: "Crisis on Umbara",
    location: "Umbara Jungle",
    zoneIds: [],
    zoneNames: ["crisis on umbara", "umbara jungle"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_copero",
    name: "A Traitor Among the Chiss",
    location: "Copero",
    zoneIds: [],
    zoneNames: ["a traitor among the chiss", "copero"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_nathema",
    name: "The Nathema Conspiracy",
    location: "Nathema Sanitarium",
    zoneIds: [],
    zoneNames: ["the nathema conspiracy", "nathema sanitarium"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_meridian",
    name: "Objective Meridian",
    location: "Corellia Shipyards",
    zoneIds: [],
    zoneNames: ["objective meridian", "corellia shipyards"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_sov",
    name: "Spirit of Vengeance",
    location: "Mandalorian Flagship",
    zoneIds: [],
    zoneNames: ["spirit of vengeance", "mandalorian flagship"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_sote",
    name: "Secrets of the Enclave",
    location: "Dantooine Enclave Ruins",
    zoneIds: [],
    zoneNames: ["secrets of the enclave", "dantooine enclave ruins"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_nul",
    name: "Ruins of Nul",
    location: "Elom Snowy Fortress",
    zoneIds: [],
    zoneNames: ["ruins of nul", "elom snowy fortress"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
  {
    id: "fp_sos",
    name: "Shrine of Silence",
    location: "Voss Undercity",
    zoneIds: [],
    zoneNames: ["shrine of silence", "voss undercity"],
    isLair: false,
    difficulties: ALL,
    groupSizes: [4],
  },
];

export const OPERATIONS_BY_ID = new Map(OPERATIONS.map((op) => [op.id, op]));

/** False when a pull reports a difficulty the operation does not offer. */
export function supportsDifficulty(operation: Operation, difficulty: Difficulty): boolean {
  return operation.difficulties.includes(difficulty);
}
